language: cpp
sudo: required

compiler: gcc

install:
    - sudo apt-get remove cmake
    - wget http://www.cmake.org/files/v3.2/cmake-3.2.1.tar.gz
    - tar -xzf cmake-3.2.1.tar.gz
    - cd cmake-3.2.1
    - sudo make install
    - cd ..
    - rm -rf cmake-3.2.1 cmake-3.2.1.tar.gz

script:
    - cmake .
    - make
    - ./tests
